### ISSUE TITLE
athena over https

### ISSUE THREAD

**Issue by georgebecerescu** [MythicAgents/Athena#14]
**Is your feature request related to a problem? Please describe.**

Seems that I am unable to do communication over https with Athena. I'm new to Mythic so maybe I am missing something.
I am trying to use Athena to callback to a Kali located on aws using the IPv4 DNS such as  https://ec2-xx-xx-xx-xx.region.compute.amazonaws.com and port 443 but seems that I am unable (no callback received).
It works over http & port 80

**Describe the solution you'd like**
A secure connection from a remote machine.

**Describe alternatives you've considered**

Maybe other communication  channel but does not seem straightforward.

**Additional context**
Mythic v2.3.13
Latest Athena git (21.10.2022)

**Comment by checkymander** [comment]
Hey thanks for the issue! I recently used Athena over HTTPS and didn't have any issues with it. Are other agents able to get through?

I don't think I accidentally pushed anything to main that could have broken HTTP/S comms, but I'll take a look to confirm.

**Comment by georgebecerescu** [comment]
Hi,

I've tried with Apollo Agent and I have the same limitation. Probably I'm missing some Mythic configuration as on aws everything seems alright. Thanks for support !

**Comment by checkymander** [comment]
no problem, good luck figuring out your issue!
