### ISSUE TITLE
Athena exe agent is starting as 16 bit application.

### ISSUE THREAD

**Issue by lsecqt** [MythicAgents/Athena#27]
**Describe the bug**
Freshly generated agent cannot run on standard Windows 10 machine, displaying the following error:
![image](https://user-images.githubusercontent.com/102690672/229620565-2d2bf785-e014-4e2c-b936-eb6c4231b44c.png)

I dedicated time to generate various executables with different "Target architecture" options, but the result was unchanged.

**To Reproduce**
1. Go to "https://127.0.0.1:7443/new/payloads"
2. Click on "ACTIONS -> Generate New Payload"
3. Chose "Windows" -> Next -> "Athena" on the dropdown.
4. Copy the following options and click "NEXT":
![image](https://user-images.githubusercontent.com/102690672/229621337-bcfd4137-dd49-4399-9c02-342df9a20328.png)
5. Click next on "Build Commands Into Agent"
6. Turn http profile, fill in your settings and click "NEXT"
7. Rename athena.zip to athena.exe and ship it to Windows 10 machine.
8. Try to execute it.

**Expected behavior**
After executing the implant, I should receive a callback on Mythic UI. During the time of the testing, no AV software is running on my Windows 10 system (21H1)

**Comment by checkymander** [comment]
Can you try the `dev` branch and let me know if you have the same issue?

**Comment by checkymander** [comment]
closing, as I haven't been able to recreate so I believe it's been resolved.
