### ISSUE TITLE
Socks Broken W/ Server Side Error

### ISSUE THREAD

**Issue by craigmar** [MythicAgents/Athena#31]
When trying to start a socks proxy on port 7004 I get the following server side error from the socks.py agent_functions script. Using a fresh clone of Athena and Mythic 3.0.0.

--------------------------------------------------------------------------------------------------------------------------------
[STDOUT]:

[STDERR]:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/mythic_container/agent_utils.py", line 331, in createTasking
    createTaskingResponse = await cmd.create_tasking(task=task)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Mythic/athena/mythic/agent_functions/socks.py", line 60, in create_tasking
    stop_res = await SendMythicRPCProxyStopCommand(port=task.args.get_arg("port"), task_id=task.id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SendMythicRPCProxyStopCommand() got an unexpected keyword argument 'port'

----------------------------------------------------------------------------------
Apollo agent's socks is working as expected and calls the SendMythicRPCProxyStartCommand differently than the athena script.
https://github.com/MythicAgents/Apollo/blob/master/Payload_Type/apollo/apollo/mythic/agent_functions/socks.py

        resp = await SendMythicRPCProxyStartCommand(MythicRPCProxyStartMessage(
            TaskID=taskData.Task.ID,
            PortType="socks",
            LocalPort=taskData.args.get_arg("port")
        ))

**Comment by checkymander** [comment]
yeah socks is currently somewhat borked, I'm working on it at this moment actually lol, hoping to have it fixed soon

**Comment by checkymander** [comment]
go ahead and check out the `socks-update` branch and let me know if that helps

**Comment by checkymander** [comment]
yolo merged into `main` lmk if you have issues

**Comment by craigmar** [comment]
SOrry running behind. Blew away mythic and rebuild fresh,  checked out the update made to the master branch, built an exe payload, ran a few commands to make sure all was sell, ran "socks {"port":"7001"}", received error "Failed to start listening on port 0, it's not exposed through docker".   It seems that the input is not being passed through. This is the same error I got when trying to fix myself.   The error comes form "/mythic-docker/src/rabbitmq/utils_proxy_traffic.go".

That function is looking for if isPortExposedThroughDocker(p.LocalPort) {

But we are sending Port

        resp = await SendMythicRPCProxyStartCommand(MythicRPCProxyStartMessage(
            TaskID=taskData.Task.ID,
            PortType="socks",
            Port=taskData.args.get_arg("port")
        ))

But, if you send LocalPort then the mythic API complains about not getting the Port variable.

TypeError: MythicRPCProxyStartMessage.__init__() missing 1 required positional argument: 'Port'

I noticed apollo is using a different image, maybe their API changed on the backend?
https://github.com/MythicAgents/Apollo/blob/master/Payload_Type/apollo/Dockerfile  "FROM itsafeaturemythic/mythic_python_dotnet:latest"


https://hub.docker.com/r/itsafeaturemythic/mythic_base_image - this image is deprecated.

**Comment by checkymander** [comment]
reopening to take a closer look, I had been testing on my local machine just fine but maybe I'm running an out of date mythic. I'll start a fresh instance in a bit

**Comment by checkymander** [comment]
To be clear in your `.env` file the parameter `MYTHIC_SERVER_DYNAMIC_PORTS` contains `7000-7010` right?

**Comment by checkymander** [comment]
Okay, I've updated `main` with the new docker image, the updated mythiccontainer, and the appropriate socks.py. Give that a try and lmk. I'll keep this open in the mean time.

**Comment by craigmar** [comment]
> To be clear in your `.env` file the parameter `MYTHIC_SERVER_DYNAMIC_PORTS` contains `7000-7010` right?

correct

**Comment by craigmar** [comment]
Confirmed working on my end. Thank you very much for your help!!
