### ISSUE TITLE
Error on http profile build

### ISSUE THREAD

**Issue by mmmmcoffee** [MythicAgents/Athena#36]
After cloning new mythic, http, and athena, and creating a payload with defaults, I get the following build error:

STDERR:
Error building payload: Traceback (most recent call last):
  File "/Mythic/athena/mythic/agent_functions/builder.py", line 378, in build
    build_msg += "Adding {} profile...".format(profile["name"]) + '\n'
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpwnltg8yh0f0eb337-3264-4f55-902b-552f234ce0c6/Athena/bin/Release/net7.0/win-x64/publish//http.json'

I believe it's because the full directory path on the way to {profile}.json may not exist yet

**Comment by checkymander** [comment]
Thanks! I'll take a look quick and see if your push fixes it. I'll have something out today.

**Comment by checkymander** [comment]
Hey, thanks for the PR. It turns out the error message was slightly misleading though. Essentially what was happening was the HTTP profile was failing to build and that's the reason that directory wasn't being created. I've fixed the issue, and pushed it to main so you should be good to go!
