### ISSUE TITLE
Athena Agent not starting

### ISSUE THREAD

**Issue by hagbartx** [MythicAgents/Athena#44]
**Describe the bug**
In a clean new mythic install the athena container is constantly restarting 

**To Reproduce**
1. Install mythic 
2. Install athena via `sudo ./mythic-cli install github https://github.com/MythicAgents/Athena`
3. Show Logs via `sudo ./mythic-cli logs athena`
4. See error:

```
Traceback (most recent call last):
  File "/Mythic/main.py", line 5, in <module>
    p = subprocess.Popen(["dotnet", "build", "--verbosity=q", "--nologo"], cwd="/Mythic/athena/agent_code/AthenaPlugins")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1917, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dotnet'
Traceback (most recent call last):
  File "/Mythic/main.py", line 5, in <module>
    p = subprocess.Popen(["dotnet", "build", "--verbosity=q", "--nologo"], cwd="/Mythic/athena/agent_code/AthenaPlugins")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Expected behavior**
athena should start

**Desktop (please complete the following information):**
 - latest Kali
 - latest Firefox

**Additional context**

looks like main.py does not find the dotnet binary in the `itsafeaturemythic/mythic_python_dotnet:latest` Image

I fixed it with a full path in main.py

```
cat main.py   
import mythic_container
from athena.mythic import *
import subprocess

p = subprocess.Popen(["/root/.dotnet/dotnet", "build", "--verbosity=q", "--nologo"], cwd="/Mythic/athena/agent_code/AthenaPlugins")

mythic_container.mythic_service.start_and_run_forever()
```

**Comment by checkymander** [comment]
huh, that's weird. Can you try `sudo ./mythic-cli install github https://github.com/MythicAgents/Athena dev` to install the `dev` branch and tell me if it's still an issue?

**Comment by hagbartx** [comment]
Ok, that's strange. Did a new install and cannot reproduce the error. Both branches working without any problems. 
Not sure what happened. Sorry for bother you.

Thank you for your work. Testing mythic/athena for an coming assessment and it is great even against EDR.

**Comment by checkymander** [comment]
It's no problem at all! Glad it's working for you, if you encounter any bugs feel free to let me know. I'm usually pretty quick about fixing them once identified.
