### ISSUE TITLE
reg plugin assumes KeyValue Kind is String

### ISSUE THREAD

**Issue by GeneralBison** [MythicAgents/Athena#52]
Going to look into implementing my own "fix" for this, but first wanted to ask if this was intentional or if I was missing something.

I'm trying to add a REG_DWORD registry key but the [RegistryAdd ](https://github.com/MythicAgents/Athena/blob/574d6942e8ddf3c3743ce0bc3080bcea677ae44f/Payload_Type/athena/athena/agent_code/AthenaPlugins/reg/reg.cs#L131C68-L131C68)function seems to only parse arguments as a String (resulting in the data kind of REG_SZ)

```c# 
string RegistryAdd(string KeyName, string keyPath, string KeyValue, string RemoteAddr, out bool error)
```

Is there a reason why you don't use the [RegistryValueKind overload](https://learn.microsoft.com/en-us/dotnet/api/microsoft.win32.registrykey.setvalue?view=net-7.0#microsoft-win32-registrykey-setvalue(system-string-system-object-microsoft-win32-registryvaluekind))? 
The RegistryKey.SetValue method _can_ infer a DWORD from an integer input, but Athena seems to pass the KeyValue as a string.

If this is functionality that would be of use, I'd be happy to make a pull request with my own (potentially janky) implementation.

**Comment by checkymander** [comment]
Hey sorry, I missed this. 

It's definitely an oversight and needs to be fixed. I'm all for you providing a fix for it, or I can do it myself. If you want to apply the fix, take a look at the `rewrite` branch as I'm currently doing a pretty big overhaul with Athena.

**Comment by GeneralBison** [comment]
Just checked the rewrite branch and it looks like this has already been added to the reg plugin.

**Comment by checkymander** [comment]
Yep! I was able to add it and confirmed it working
