### ISSUE TITLE
Parsing issues in ls

### ISSUE THREAD

**Issue by checkymander** [MythicAgents/Athena#66]
Path parsing is broken in Linux and Mac when using the FileBrowser

parent is returning "" when it should probably be returning "/"

Due to this file browser reports the path as "etc\ModemManager"

![image](https://github.com/MythicAgents/Athena/assets/26147220/6571dc4f-8703-4d92-916d-1f98e8fe7fec)

Starts working again once you're out of the base directory (via filebrowser)

![image](https://github.com/MythicAgents/Athena/assets/26147220/628f35eb-bbc9-4f9e-8796-2deb6a38dc48)

likely fixes
1.) Properly handle path's where it's just `/`
2.) When parent is "" or "/" return the parent as "//" to unfuck things

**Comment by checkymander** [comment]
In MacOS, `ls` returns a root path as `/System` instead of `/` confirm if that's correct

**Comment by tr41nwr3ck** [comment]
I was not able to replicate this

**Comment by checkymander** [comment]
Seems to be fine outside of gitlab runners
