### ISSUE TITLE
Slack profile does not compile.

### ISSUE THREAD

**Issue by charnim** [MythicAgents/Athena#69]
**Describe the bug**
Default settings athena payload with slack profile does not compile.

the error:

Traceback (most recent call last):
  File "/Mythic/athena/mythic/agent_functions/builder.py", line 369, in build
    await self.buildSlack(agent_build_path, c2)
  File "/Mythic/athena/mythic/agent_functions/builder.py", line 144, in buildSlack
    baseConfigFile = open("{}/Agent.Profiles.Slack/Base.txt".format(agent_build_path.name), "r").read()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp5rba2g65efa69a08-f0d1-45a7-a274-04b8839e533e/Agent.Profiles.Slack/Base.txt'

Logging to the container shows the directory /tmp/tmp5rba2g65efa69a08-f0d1-45a7-a274-04b8839e533e does not exist.

**Comment by checkymander** [comment]
Hey sorry about that! The slack profile didn't survive the agent rewrite. I'm currently in the process of rewriting it and figuring out what the new version is going to look like. 

There's a beta version of the discord profile though if you want to check out the `feature-nidhogg` branch

**Comment by Sybrid203** [comment]
Any update on this one? @checkymander
Can you maybe restore the old branch that did work so we can pull from it and work on top of that one instead of the new one?

**Comment by tr41nwr3ck** [comment]
Currently we have no plans of reimplementing slack at this time.
